// var x = require("./module1");
// var matematika = require("./module2");
// matematika.plus(4,2);
// matematika.minus(4,2);
// users("Developer");
// var users = require("./moduleb");
// var gamers = users("Gamer");
// var developers = users("Developer");
// console.log(developers);
var randomize = require("./randomize");
var users = randomize(["Danilo","Hamza","Marko","Lana","Vildana"]);
console.log(users);